#!/bin/bash

wget -O HFI_SkyMap_100_2048_R3.01_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_100_2048_R3.01_full.fits"
wget -O HFI_SkyMap_100-field-IQU_2048_R3.00_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_100-field-IQU_2048_R3.00_full.fits"
wget -O HFI_SkyMap_143_2048_R3.01_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_143_2048_R3.01_full.fits"
wget -O HFI_SkyMap_143-field-IQU_2048_R3.00_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_143-field-IQU_2048_R3.00_full.fits"
wget -O HFI_SkyMap_217_2048_R3.01_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_217_2048_R3.01_full.fits"
wget -O HFI_SkyMap_217-field-IQU_2048_R3.00_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_217-field-IQU_2048_R3.00_full.fits"
wget -O HFI_SkyMap_353-psb_2048_R3.01_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_353-psb_2048_R3.01_full.fits"
wget -O HFI_SkyMap_353-psb-field-IQU_2048_R3.00_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_353-psb-field-IQU_2048_R3.00_full.fits"
wget -O HFI_SkyMap_545_2048_R3.01_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_545_2048_R3.01_full.fits"
wget -O HFI_SkyMap_545-field-Int_2048_R3.00_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_545-field-Int_2048_R3.00_full.fits"
wget -O HFI_SkyMap_857_2048_R3.01_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_857_2048_R3.01_full.fits"
wget -O HFI_SkyMap_857-field-Int_2048_R3.00_full.fits "http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=HFI_SkyMap_857-field-Int_2048_R3.00_full.fits"